---

- name: create-ou
  hosts: domain_controller
  gather_facts: no

  tasks:
  - name: load script from jinja template
    win_template:
      src: files/windows/create-ou.ps1.j2
      dest: C:\480\create-ou.ps1
  - name: run the script
    async: 10
    poll: 0
    win_shell:
      C:\480\create-ou.ps1