---

- name: Enable RDP
  hosts: windows
  gather_facts: yes
  
  tasks:
  - name: Enable Remote Desktop
    win_shell: |
      Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

  - name: Only allow domain users
    win_shell: |
      Enable-NetFirewallRule -DisplayGroup "Remote Desktop"