---

- name: windows-software
  hosts: windows_workstation
  gather_facts: yes

  tasks:
  - name: Install 7zip
    win_chocolatey:
      name: 7zip
      state: present

  - name: Install chrome
    win_chocolatey:
      name: googlechrome
      state: present
      ignore_checksums: yes

  - name: Install git
    win_chocolatey:
      name: git
      state: present

  - name: Install Visual Studio Code
    win_chocolatey:
      name: vscode.install
      state: present

  - name: Install Putty
    win_chocolatey:
      name: putty
      state: present

  - name: Install Python3
    win_chocolatey:
      name: python3
      state: present

  - name: Install notepad++ as something I chose
    win_chocolatey:
      name: notepadplusplus
      state: present

  - name: Upgrade installed packages
    win_chocolatey:
      name: all
      state: latest